name: "Deploy CodigoFacilito"
on: 
  push:
    branches: ["main"]

jobs: 
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"